services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: node
    container_name: studytime
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_DB=$MONGO_DB
    ports: 
      - "8080:8080"
    volumes:
      - .:/home/gis-semesterprojekt
      - node_modules:/home/gis-semesterprojekt/node_modules
    networks:
      - studytime
    working_dir: /home/gis-semesterprojekt
    command:
      "npm start"


  db:
    image: mongo
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - studytime


networks:
  studytime:
    driver: bridge

volumes:
  dbdata:
  node_modules:

